In [22]:
import numpy as np 
import scipy
a = np.array([[30, 100, 20, 80], [50, 40, 70, 60], [90, 60, 10, 50]])
c = np.array([230, 220, 210])
d = np.array([170, 200, 100, 190])
e = np.outer(c, d) / 660
print(e)
print(sum(sum((a - e)**2 / e)) / 6)
b = scipy.stats.chisquare(a, e)
print(b)


[[59.24242424 69.6969697  34.84848485 66.21212121]
 [56.66666667 66.66666667 33.33333333 63.33333333]
 [54.09090909 63.63636364 31.81818182 60.45454545]]
21.597116192014557
Power_divergenceResult(statistic=array([39.05736208, 24.04968944, 61.62111801,  4.85452762]), pvalue=array([3.30218642e-09, 5.99344180e-06, 4.16048767e-14, 8.82780478e-02]))


In [5]:
print(b)

Power_divergenceResult(statistic=array([32.94117647, 28.        , 62.        ,  7.36842105]), pvalue=array([7.02933783e-08, 8.31528719e-07, 3.44247711e-14, 2.51169961e-02]))


In [12]:
c = np.array([[20, 25], [30, 35], [40, 45]])
d = np.array([[45, 40], [50, 45]])
print(sum((c[:, 1] - c[:, 0])**2 * 10 / (c[:, 1]**2 +3)))
print(sum((d[:, 1] - d[:, 0])**2 / (d[:, 1]**2 + 1)))

0.7249463955994733
0.027954825864634207


In [11]:
25 * (10 / 628 + 10 / (1228) + 10 / 2028 + 1 / 1601 + 1/2026)

0.7529012214641075