In [9]:
import torch
import numpy as np
a = [1, 2, 3]
b = np.arange(3) + 4
b = b.astype(np.int32)
print(b.dtype)
t_a = torch.tensor(a)
t_b = torch.from_numpy(b)
print(t_a.dtype)
print(t_b.dtype)
t_a_new = t_a.to(torch.int32)
print(t_a_new.dtype)

int32
torch.int64
torch.int32
torch.int32


In [21]:
t_ones = torch.ones(2, 3)
print(t_ones.shape)
rand_tensor = torch.rand(2, 2, 2)
print(rand_tensor)
rand_tensor_tr = torch.transpose(rand_tensor, 1, 2)
print(rand_tensor_tr)
print(rand_tensor_tr.reshape(8))
a = torch.zeros(1, 2, 3, 2, 1)
b = torch.squeeze(a)
print(b.shape)
c = torch.squeeze(a, 0)
print(c.shape)


torch.Size([2, 3])
tensor([[[8.9250e-01, 7.2552e-01],
         [3.5556e-01, 8.8382e-04]],

        [[2.1454e-01, 6.7671e-01],
         [8.8789e-01, 3.0504e-01]]])
tensor([[[8.9250e-01, 3.5556e-01],
         [7.2552e-01, 8.8382e-04]],

        [[2.1454e-01, 8.8789e-01],
         [6.7671e-01, 3.0504e-01]]])
tensor([8.9250e-01, 3.5556e-01, 7.2552e-01, 8.8382e-04, 2.1454e-01, 8.8789e-01,
        6.7671e-01, 3.0504e-01])
torch.Size([2, 3, 2])
torch.Size([2, 3, 2, 1])


In [32]:
torch.manual_seed(1)
t1 = torch.rand(5, 2) * 2 - 1
t2 = torch.normal(mean = 0, std = 1, size = (5, 2))
t3 = torch.concatenate((t1, t1))
t4 = t3.clone().detach()
t3[t4 == t4[0, 0]] = 1
print(t3)
print(t1)
print(t2)

tensor([[ 1.0000, -0.4414],
        [-0.1939,  0.4694],
        [-0.9414,  0.5997],
        [-0.2057,  0.5087],
        [ 0.1390, -0.1224],
        [ 1.0000, -0.4414],
        [-0.1939,  0.4694],
        [-0.9414,  0.5997],
        [-0.2057,  0.5087],
        [ 0.1390, -0.1224]])
tensor([[ 0.5153, -0.4414],
        [-0.1939,  0.4694],
        [-0.9414,  0.5997],
        [-0.2057,  0.5087],
        [ 0.1390, -0.1224]])
tensor([[ 0.8590,  0.7056],
        [-0.3406, -1.2720],
        [-1.1948,  0.0250],
        [-0.7627,  1.3969],
        [-0.3245,  0.2879]])


Split Stack Concatenate tensors

In [62]:
torch.manual_seed(42)
t = torch.rand(6)
t_splits = t.chunk(3, dim=-1)
t_splits2 = t.chunk(3, dim = 0)
t_split42 = t.split(split_size=[4, 2])

print(t_split42)
q = torch.cat((t_split42[0], t_split42[1]), axis = 0)
print(q)
t_stack = torch.stack((t_splits[0], t_splits[1], t_splits[2]), axis = 0)
print(t_stack.T)

(tensor([0.8823, 0.9150, 0.3829, 0.9593]), tensor([0.3904, 0.6009]))
tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009])
tensor([[0.8823, 0.3829, 0.3904],
        [0.9150, 0.9593, 0.6009]])


In [68]:
from torch.utils.data import DataLoader
t = torch.arange(6, dtype = torch.float32)
data_loader = DataLoader(t)
for it in data_loader:
    print(it)

tensor([0.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([4.])
tensor([5.])


In [74]:
data_loader = DataLoader(t, batch_size=3, drop_last = False)
for i, batch in enumerate(data_loader, 1):
    print(f'batch {i}', batch)


batch 1 tensor([0., 1., 2.])
batch 2 tensor([3., 4., 5.])


In [80]:
t_x = torch.rand([4, 3], dtype = torch.float32)
t_y = torch.arange(4)
from torch.utils.data import Dataset, TensorDataset
class JointDataset(Dataset):
    def __init__(self, x, y):
        self.x = x
        self.y = y
    def __len__(self):
        return len(x)
    def __getitem__(self, idx):
        return self.x[idx], self.y[idx]
joint_dataset = TensorDataset(t_x, t_y)
print(joint_dataset[0][0])

tensor([0.2418, 0.1591, 0.7653])


In [86]:
data_loader = DataLoader(dataset = joint_dataset, batch_size = 2, shuffle = False)
for i, batch in enumerate(data_loader, 1):
    print(f'batch {i}:', 'x: ', batch[0], '\n\t y: ', batch[1])

batch 1: x:  tensor([[0.2418, 0.1591, 0.7653],
        [0.2979, 0.8035, 0.3813]]) 
	 y:  tensor([0, 1])
batch 2: x:  tensor([[0.7860, 0.1115, 0.2477],
        [0.6524, 0.6057, 0.3725]]) 
	 y:  tensor([2, 3])


In [93]:
data_loader = DataLoader(dataset = joint_dataset, batch_size = 2, shuffle = True)
for i, batch in enumerate(data_loader, 4):
    print(f'batch {i}:', 'x: ', batch[0], '\n\t y: ', batch[1])

batch 4: x:  tensor([[0.6524, 0.6057, 0.3725],
        [0.7860, 0.1115, 0.2477]]) 
	 y:  tensor([3, 2])
batch 5: x:  tensor([[0.2418, 0.1591, 0.7653],
        [0.2979, 0.8035, 0.3813]]) 
	 y:  tensor([0, 1])


In [95]:
for epoch in range(3):
    print(f'epoch {epoch+1}')
    for i, batch in enumerate(data_loader, 1):
        print(f'batch {i}:', 'x: ', batch[0], '\n\t y: ', batch[1])

epoch 1
batch 1: x:  tensor([[0.7860, 0.1115, 0.2477],
        [0.2418, 0.1591, 0.7653]]) 
	 y:  tensor([2, 0])
batch 2: x:  tensor([[0.6524, 0.6057, 0.3725],
        [0.2979, 0.8035, 0.3813]]) 
	 y:  tensor([3, 1])
epoch 2
batch 1: x:  tensor([[0.2979, 0.8035, 0.3813],
        [0.6524, 0.6057, 0.3725]]) 
	 y:  tensor([1, 3])
batch 2: x:  tensor([[0.7860, 0.1115, 0.2477],
        [0.2418, 0.1591, 0.7653]]) 
	 y:  tensor([2, 0])
epoch 3
batch 1: x:  tensor([[0.7860, 0.1115, 0.2477],
        [0.2979, 0.8035, 0.3813]]) 
	 y:  tensor([2, 1])
batch 2: x:  tensor([[0.2418, 0.1591, 0.7653],
        [0.6524, 0.6057, 0.3725]]) 
	 y:  tensor([0, 3])
